# Generated by Django 5.0.4 on 2024-04-22 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_dynamic_location", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="field_type",
            field=models.CharField(
                choices=[("jmeter", "JMX"), ("testlab", "Cypress")], max_length=20
            ),
        ),
    ]
