# Generated by Django 5.0.4 on 2024-05-06 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_dynamic_location", "0003_agent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agent",
                to="agent_dynamic_location.agent",
            ),
        ),
    ]
