# Generated by Django 5.0.6 on 2024-05-24 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_dynamic_location", "0007_customtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_info_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("before", "Before"),
                            ("after", "After"),
                            ("on-execution", "OnExecution"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "container_ref_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cpu_usage", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "total_memory_gb",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "available_memory_gb",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "used_memory_gb",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "memory_usage_percent",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bytes_sent_mb",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bytes_received_mb",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_system_info",
                        to="agent_dynamic_location.agent",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_system_info",
                        to="agent_dynamic_location.job",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_system_info",
                        to="agent_dynamic_location.privatelocation",
                    ),
                ),
            ],
        ),
    ]
