# Generated by Django 5.0.6 on 2024-05-24 16:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent_dynamic_location", "0008_systeminfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="systeminfo",
            name="ref",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
