# Generated by Django 5.0.4 on 2024-04-24 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performace_test", "0004_testcontainersruns_raw_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="JmeterTestContainersRuns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("container_id", models.CharField(max_length=255, null=True)),
                ("container_status", models.CharField(max_length=255, null=True)),
                ("container_labels", models.CharField(max_length=255, null=True)),
                ("container_name", models.CharField(max_length=255, null=True)),
                ("container_short_id", models.CharField(max_length=255, null=True)),
                ("container_logs_str", models.TextField(null=True)),
                (
                    "ref",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("json", models.JSONField(null=True)),
                ("raw_data", models.JSONField(null=True)),
                (
                    "test_file",
                    models.FileField(
                        null=True,
                        upload_to="uploads/performace_tests/JmeterTestContainersRuns/",
                    ),
                ),
                (
                    "client_reference_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jmeter_container_runs",
                        to="performace_test.performacetestsuite",
                    ),
                ),
            ],
        ),
    ]
