# Generated by Django 5.0.4 on 2024-04-29 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performace_test", "0005_jmetertestcontainersruns"),
    ]

    operations = [
        migrations.CreateModel(
            name="JmeterTestArtifacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=255, null=True)),
                (
                    "files",
                    models.FileField(upload_to="uploads/performace_tests/jmeter/"),
                ),
                (
                    "container_runs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jmeter_runs_artifacts",
                        to="performace_test.jmetertestcontainersruns",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jmeter_suite_artifacts",
                        to="performace_test.performacetestsuite",
                    ),
                ),
            ],
        ),
    ]
