const userActionsOptions = [
  "click",
  "hover",
  "dragDrop",
  "keyPress",
  "Assign",
  "Capturescreenshot",
  "ExecuteJavascript",
  "Pause",
  "ExitTest",
  "openURL",
  "goBack",
  "refresh",
  // "openNewTab",
  // "closeTab",
  "Elementispresent",
  "ElementIsNotPresent",
  "ElementIsVisible",
  "ElementIsNotVisible",
  "ElementTextEqual",
  "ElementTextDoesNotEqual",
  "ElementTextContains",
  "ElementTextDoesNotContains",
  "JavaScriptReturnsTrue",
  "CheckAccessibility",
  "SetVariable",
  "ExtractFromElement",
  "ExtractFromJavaScript",
  "ImportTestFromSteps"
].map((action) => ({ label: action, value: action }));

 export default userActionsOptions;
