const userActionsOptions = [
    { label: "Click", value: "click" },
    { label: "Hover", value: "hover" },
    { label: "Drag and Drop", value: "dragDrop" },
    { label: "Key Press", value: "keyPress" },
    { label: "Open URL", value: "openURL" },
    { label: "Go Back", value: "goBack" },
    { label: "Refresh", value: "refresh" },
    { label: "Open New Tab", value: "openNewTab" },
    { label: "Close Tab", value: "closeTab" },
    { label: "Switch to Tab", value: "switchToTab" },
    { label: "Open New Window", value: "openNewWindow" },
    { label: "Close Window", value: "closeWindow" },
    { label: "Switch to Window", value: "switchToWindow" },
    { label: "Accept Alert", value: "acceptAlert" },
    { label: "Dismiss Alert", value: "dismissAlert" },
    { label: "Get Alert Text", value: "getAlertText" },
    { label: "Send Text to Alert", value: "sendTextToAlert" },
    { label: "Switch to Frame/IFrame", value: "switchToFrame" },
    { label: "Switch Back from Frame/IFrame", value: "switchBackFromFrame" },
    { label: "Wait for Element to be Visible", value: "waitForVisible" },
    { label: "Wait for Element to be Clickable", value: "waitForClickable" },
    { label: "Implicit Wait", value: "implicitWait" },
    { label: "Explicit Wait", value: "explicitWait" },
    { label: "Maximize Window", value: "maximizeWindow" },
    { label: "Minimize Window", value: "minimizeWindow" },
    { label: "Set Window Size", value: "setWindowSize" },
    { label: "Set Window Position", value: "setWindowPosition" },
  ];
  
  export default userActionsOptions;
  