# Generated by Django 5.0.6 on 2024-06-06 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_url", models.URLField()),
                ("max_depth", models.IntegerField(default=10)),
                ("client_reference_id", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("action", models.CharField(max_length=255)),
                ("selector", models.CharField(max_length=255)),
                ("is_start_node", models.BooleanField(default=False)),
                ("client_reference_id", models.CharField(max_length=255)),
                ("element_info", models.JSONField(blank=True, null=True)),
                ("depth", models.IntegerField(blank=True, null=True)),
                (
                    "crawl_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="web_crawler.crawlrequest",
                    ),
                ),
                (
                    "previous_node",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_nodes",
                        to="web_crawler.node",
                    ),
                ),
            ],
        ),
    ]
