# Generated by Django 5.0.6 on 2024-06-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_crawler", "0002_node_visited"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="action",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="node",
            name="selector",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
